blank_issues_enabled: true
contact_links:
  - name: Support & Community ğŸ’
    url: https://discord.com/invite/solidjs
    about: "This issue tracker is not for support questions. Our Discord server hosts the community of Solid users. Come join us to discuss Solid or find assistance!"
