name: Spellcheck

on:
  push:
    branches:
      - "**"
    paths:
      - "**/routes/**"
      - "**.mdx"
  pull_request:
    branches:
      - "**"
    paths:
      - "**/routes/**"
      - "**.mdx"

permissions:
  contents: read

jobs:
  spellcheck:
    name: GitHub Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Check Changed Files
        uses: tj-actions/changed-files@v45
        id: changed_files
        with:
          files: |
            src/routes/**/*.mdx
      - name: Run Spellcheck
        id: spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          config_path: ./.github/actions/spelling/.spellcheck.yml
          task_name: Markdown
          source_files: ${{ steps.changed_files.outputs.all_changed_files }}
